model:
  m: 5.5,               # mass
  I: 9.2413606e-03,     # moment of inertia
  length: 0.235,        # length
  width: 0.3,           # width
  height: 0.38,         # height
  leg_length: 0.38,     # leg length
  l1: 0.19,             # upper leg length
  l2: 0.19,             # lower leg length
  l3: 0.235,            # com-hip distance
  dmin: 0.20,           # minimum distance
  l_box: 0.250,         # box length
  w_box: 0.3,           # box width
  gamma: 100.0,         # penalty on the distance
  gamma_v: 100.0,       # penalty on the velocity

cost:
  k_force: 0.1,         # force cost
  k_vel: 0.1,           # vel cost
  k_pos: 0.1,           # pos cost
  alpha: 0.0,           # x terminal cost
  beta: 0.0,            # z terminal cost
  gamma: 0.0,           # theta terminal cost


solver:
  max_iter: 100,        # maximum iterations
  tol: 1e-6,            # tolerance
  acceptable_tol: 1e-4, # acceptable tolerance
  print_level: 0,       # print level