optimization_problem:
  initial_state: '[0.03, -0.0075, 0.0]'
  initial_control: '[0.0, 0.0, 0.0]'
  final_state: '[0.0, 0.0, 0.0]'
  horizon: 0.5,
  N: 20,
  n_int: 4,
  input_lower_bound: '[-0.5, -0.5, -0.5]'
  input_upper_bound: '[0.5, 0.5, 0.5]'
  state_lower_bound: '[-0.1, -0.1, -0.1]'
  state_upper_bound: '[0.1, 0.1, 0.1]'
  slope: 0.0,

cost:
  k_force: 0.1,         # force cost
  k_vel: 0.1,           # vel cost
  k_pos: 0.1,           # pos cost
  alpha: 0.0,           # x terminal cost
  beta: 0.0,            # z terminal cost
  gamma: 0.0,           # theta terminal cost


solver:
  ipopt:
    max_iter: 100,        # maximum iterations
    tol: 1e-6,            # tolerance
    acceptable_tol: 1e-4, # acceptable tolerance
    print_level: 0,       # print level
  