optimization_problem:
  initial_state: [0.0, 0.0, 0.28, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.235, 0.17, 0.0, 0.235, -0.17, 0.0, -0.235, 0.17, 0.0, -0.235, -0.17, 0.0]
  final_state: [0.0, 0.0, 0.0]
  horizon: 1.0  # [s]
  N: 30
  n_int: 2
  input_lower_bound: [-100.0, -100.0, 0.0, -100.0, -100.0, 0.0, -100.0, -100.0, 0.0, -100.0, -100.0, 0.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0]
  input_upper_bound: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]
  state_lower_bound: [-100.0, -100.0, 0.0, -0.18, -0.18, -1.0, -1.0, -1.0, -1.0, -2.0, -2.0, -2.0, -100.0, -100.0, 0.0, -100.0, -100.0, 0.0, -100.0, -100.0, 0.0, -100.0, -100.0, 0.0]
  state_upper_bound: [100.0, 100.0, 2.0, 0.18, 0.18, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 100.0, 100.0, 2.0, 100.0, 100.0, 2.0, 100.0, 100.0, 2.0, 100.0, 100.0, 2.0]
  slope: 0.0
  x_step: 0.3           # x step
  y_step: 0.2           # y step
  z_step: 0.0           # z step


cost:
  k_pos: 500.0           # pos cost
  k_orientation: 100.0   # orientation cost
  k_vel: 1.0           # vel cost
  k_omega: 1.0         # omega cost
  k_foot: 1.0          # foot cost
  k_force: 1.0         # force cost
  k_foot_vel: 1.0      # foot vel cost
  terminal:
    alpha: 10.0           # x terminal cost
    beta: 10.0            # z terminal cost
    gamma: 10.0           # theta terminal cost

solver:
  ipopt:
    max_iter: 200        # maximum iterations
    tol: 1.0e-06            # tolerance
    acceptable_tol: 1.0e-04 # acceptable tolerance
    print_level: 5       # print level
    # verbose: false         # verbose
    # print_time: true     # print time
  